## Time-of-Flight Distance Unit (VL53L1X) M5stack  SKU: U172
## Remark: I2C grove cable max 2 mtr
## https://shop.m5stack.com/products/time-of-flight-distance-unit-vl53l1x

external_components:
  - source: github://mrtoy-me/esphome-vl53l1x@main
    components: [ vl53l1x ]
    refresh: 0s

sensor:
  # VL53L1X TOF
  - platform: vl53l1x
    i2c_id: bus_a
    address: 0x29
    distance_mode: short
    update_interval: 60s
    distance:
      # name: My Raw Distance # comment out if not needed in HA UI
      id: vl53l1x_raw_distance
    range_status:
      # name: My Range Status # comment out if not needed in HA UI
      id: vl53l1x_range_status

  - platform: template
    name: ${clack_distance_tof}
    id: clack_distance_tof
    update_interval: 60s
    unit_of_measurement: "cm"
    accuracy_decimals: 1
    device_class: distance
    state_class: measurement
    icon: mdi:ruler
    internal: false
    lambda: |-
      if (id(vl53l1x_range_status).state > 0) {
        return NAN;
      } else {
        return id(vl53l1x_raw_distance).state;
      }
    filters:
      - lambda: |-
          if (isnan(x)) {
            return 0;
          } else {
            return x;
          }
      - lambda: return x/10;
      - clamp:
          min_value: 0.0
          max_value: 230.0
      - delta: 0.2
    on_value:
      then:
        - lambda: |-
            id(last_distance) = float(x);
        - component.update: clack_distance
