## Time-of-Flight Distance Ranging Sensor Unit (VL53L0X) M5stack  SKU: U010
## Remark: I2C grove cable max. 5 mtr
## https://shop.m5stack.com/products/tof-sensor-unit

sensor:
  # VL53L0X TOF
  - platform: vl53l0x
    id: clack_distance_tof
    name: ${clack_distance_tof}
    unit_of_measurement: cm
    accuracy_decimals: 1
    icon: mdi:ruler
    device_class: distance
    state_class: measurement
    internal: false
    address: 0x29
    update_interval: 10s
    long_range: false
    filters:
      - lambda: |-
          if (isnan(x)) {
            return 0;
          } else {
            return x;
          }
      - lambda: return x*100;
      - clamp:
          min_value: 0.0
          max_value: 200.0
      - median:
          window_size: 3
          send_every: 2
          send_first_at: 1
      - delta: 0.2
      - round: 1
    on_value:
      then:
        - lambda: |-
            id(last_distance) = float(x);
        - component.update: clack_distance
