### ESP32 S3 used is a M5stack Atom S3 lite

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 8MB
  ## Atom S3 lite
  framework:
    type: esp-idf
    version: recommended
    # Custom sdkconfig options
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_BT_ENABLED: n

i2c:
  ## use I2C bus external, not on ESP GPIO1 and GPIO2
  - id: bus_a
    sda: GPIO6
    scl: GPIO5
    scan: false
    frequency: 50000Hz

binary_sensor:
  ## temporary test button for testing water meter pulse
  # Binary sensor "clack_use_test_button"
  - id: clack_use_test_button
    name: clack_use_test_button
    platform: template
    internal: true
    filters:
      - delayed_on_off: 50ms
    on_press:
      then:
        - lambda: |-
            ESP_LOGI("main", "Water meter freeze? %s", id(water_meter_freeze) ? "Yes" : "No");
        - if:
            condition:
              lambda: 'return id(water_meter_freeze) == false;'
            then:
              # We have to calculate the number of pulses by multiplying the liters with the pulse per liter setting.
              # Because of the precision of 1 decimal for the total sensor, adding 0.1 L is not always visible.
              # The pulse_meter sensor has a precision of 2 decimals, which is a little more precise.
              - pulse_meter.set_total_pulses:
                  id: clack_flow_rate
                  value: !lambda |-
                    return (id(totalWaterUsage) + 0.1) * id(pulse_per_liter);

  # Binary sensor "init_state"
  - platform: template
    name: Block regen
    id: init_state
    internal: false
    lambda: |-
      if (id(wait_on_delay)) {
        return true;
      } else {
        return false;
      }


# ## temporary test button for testing regeneration pulse
switch:
  # Chlorinator Relay
  # Switch "chlorinator_relay"
  - platform: gpio
    pin:
      number: GPIO8
      inverted: false
    name: ${clack_chlorinator}
    id: chlorinator_relay
    icon: mdi:bacteria
    entity_category: config

button:
  # Button "clack_use_tst_but"
  - platform: template
    name: ${clack_use_tst_but}
    id: clack_use_tst_but
    on_press:
      then:
        - binary_sensor.template.publish:
            id: clack_use_test_button
            state: true
        - delay: 100ms
        - binary_sensor.template.publish:
            id: clack_use_test_button
            state: false

  # Button "clack_resinclean_reset_button"
  - platform: template
    name: ${clack_resinclean_reset_button}
    id: clack_resinclean_reset_button
    on_press:
      - lambda: |-
          id(resinclean_last) = id(sntp_time).now().timestamp;
      - component.update: clack_resinclean_last

  # Button "clack_reset_but_last_dist"
  - platform: template
    name: ${clack_reset_but_last_dist}
    id: clack_reset_but_last_dist
    on_press:
      then:
        - component.update: clack_distance_tof
        - lambda: |-
            id(saltfill_last) = id(sntp_time).now().timestamp;
        - component.update: clack_saltfill_last

  # Button "clack_regen_stop_script"
  - platform: template
    name: ${clack_regen_stop_script}
    id: clack_regen_stop_script
    on_press:
      then:
        - script.stop: cycle_steps_post_upflow
        - script.stop: cycle_steps_pre_upflow
        - script.stop: cycle_steps_post_downflow
        - script.stop: cycle_steps_pre_downflow
        - script.execute: reset_cycle_steps
        - script.wait: reset_cycle_steps
