substitutions:
  # General substitutions:
  name: clack
  friendly_name: Clack
  device_description: "Esphome component for Clack DV (WSPI) softener with TOF sensor saltlevel detection"
  timezone: "Europe/Amsterdam"
  # Interval substitutions:
  salt_level_update_interval: 30s
  watermeter_update_interval: 600s # 10 minutes
  clack_height_update_interval: 600s

### In order to use other language fix clack-label filename below:
### Currently supported languages are: en (English), nl (Dutch) and fr (French).
### ESP32-Atom-s3 is a M5STACK Atom s3 lite
### tof1 is a VL53L0X M5stack. Distance measure up to 2 mtr. I2C grove cable max 6 mtr length
### tof2 is a VL53L1X M5stack (ToF4M). Distance measure up to 4 mtr. I2C grove cable max 2 mtr length

packages:
  remote_package:
    url: https://github.com/fonske/clack-reader-v4
    ref: main
    refresh: 0s
    files: [ 
      esphome/clack_dv/.clack-base.yaml,
#     esphome/clack_dv/.tof1.yaml,
      esphome/clack_dv/.tof2.yaml,
      esphome/clack_dv/.waterflow.yaml,
      esphome/clack_dv/.clack-optional.yaml,
#      esphome/clack_dv/.clack-labels-nl.yaml,
      esphome/clack_dv/.clack-labels-en.yaml,
      esphome/clack_dv/board-esp32-atom-s3.yaml,
    ]

## for developing/testing, uncomment local includes and comment out above remote_package packages part.
#packages:
##  substitutions: !include clack_dv/.clack-labels-en.yaml
#  substitutions: !include clack_dv/.clack-labels-nl.yaml
#  device_base1:  !include clack_dv/board-esp32-atom-s3.yaml
#  device_base2:  !include clack_dv/.clack-base.yaml
##  device_base3: !include clack_dv/.tof1.yaml
#  device_base3:  !include clack_dv/.tof2.yaml
#  device_base4:  !include clack_dv/.waterflow.yaml
#  device_base4:  !include clack_dv/.clack-optional.yaml

time:
  - platform: sntp
    id: sntp_time
    timezone: ${timezone}
    # Enable this with your own NTP server if your device is on a no internet IOT lan. 
    #servers: 192.168.X.X
#    servers:
#     - 0.pool.ntp.org
#     - 1.pool.ntp.org
#     - 2.pool.ntp.org   

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: light
#  reboot_timeout: 0s

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name}"
    password: "configesp"
    ap_timeout: 30s

# Enable Over The Air Updates
ota:
  platform: esphome
#  password: !secret clack_ota_password

# Enable captive portal
captive_portal:
  
# Enable logger
logger:
  baud_rate: 0
  logs:
    esp32.preferences: DEBUG
    sensor: DEBUG
    text_sensor: DEBUG
    binary_sensor: DEBUG
    switch: DEBUG
    button: DEBUG
    number: DEBUG
    climate: DEBUG
    component: ERROR

# Enable Web server.
web_server:
  port: 80